export const CARSELECT_RECIEVED_SUCCESS = "CARSELECT_RECIEVED_SUCCESS";
export const CARSELECT_RECIEVED_FAILED = "CARSELECT_RECIEVED_FAILED";
export const CARSELECT_LOADING_START = "CARSELECT_LOADING_START";
export const CARSELECT_LOADING_COMPLETE = "CARSELECT_LOADING_COMPLETE";

export const FINDCAR_GET_SUCCESS = "FINDCAR_GET_SUCCESS";
export const FINDCAR_GET_FAILED = "FINDCAR_GET_FAILED";

export const COLLECTIONSLIDER_GET_SUCCESS = "COLLECTIONSLIDER_GET_SUCCESS";
export const COLLECTIONSLIDER_LOADING_START = "COLLECTIONSLIDER_LOADING_START";
export const COLLECTIONSLIDER_GET_FAILED = "COLLECTIONSLIDER_GET_FAILED";
export const COLLECTIONSLIDER_LOADING_COMPLETE = "COLLECTIONSLIDER_LOADING_COMPLETE";